### ISSUE TITLE
Start work on getting full collection of OpenAlex

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ai_genomics#23]

**Comment by Jack-Vines** [comment]
(Possibly interim) location for data files: s3://metaflow-s3-d9gy/data/OpenAlexFlow

Will contain: 

All genomics papers
All institutions
All venues
All concepts

A few notes on updated methodology;
Because of the following:
1. Processing all works is expensive, time consuming and space consuming
2. There seems to not be any massive benefit of having all works when the API functions so well
3. It costs OpenAlex money too

I've moved to a API approach of extracting works, where you provide a list of relevant concepts, and the flow extracts all papers (for reference extracting every Genomics work takes less than 15 minutes).
The institutions, venues and concepts are small enough datasets that it still makes sense to collect the whole datasets for these.

**Comment by india-kerle** [comment]
@Jack-Vines what's the status on this? Can we go ahead and close?

**Comment by Jack-Vines** [comment]
Yeah we can close this :)
